# Generated by Django 6.0.3 on 2026-03-19 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attempt',
            name='learning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='api.learning'),
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='learning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_choices', to='api.learning'),
        ),
        migrations.AddField(
            model_name='response',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.attempt'),
        ),
        migrations.AddField(
            model_name='response',
            name='selected_question_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_responses', to='api.questionchoice'),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='api.job'),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='prerequisite_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_roadmaps', to='api.skill'),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='api.skill'),
        ),
        migrations.AddField(
            model_name='learning',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnings', to='api.skill'),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('attempt', 'question_group_id')},
        ),
        migrations.AlterUniqueTogether(
            name='roadmap',
            unique_together={('job', 'skill')},
        ),
    ]
