# Generated by Django 6.0.3 on 2026-03-20 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='UserResponse',
        ),
    ]
