# Generated by Django 6.0.3 on 2026-03-20 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_response_userresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionchoice',
            name='recommended_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_question_choices', to='api.job'),
        ),
    ]
