# Generated by Django 6.0.3 on 2026-03-21 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_questionchoice_recommended_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='recommended_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulting_attempts', to='api.job'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
