# Generated by Django 6.0.3 on 2026-03-23 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_attempt_recommended_job_attempt_score'),
        ('api', '0005_survey'),
    ]

    operations = [
    ]
