# Generated by Django 6.0.3 on 2026-03-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20260323_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionchoice',
            name='recommended_job',
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='job_scores',
            field=models.JSONField(blank=True, default=dict, help_text="직무별 가중치 (예: {'DaS': 3, 'MLO': 1})"),
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='question_type',
            field=models.CharField(choices=[('Quiz', '퀴즈'), ('Test_B', '테스트(입문자)'), ('Test_E', '테스트(전문가)')], max_length=10),
        ),
    ]
