# Generated by Django 5.0.6 on 2026-05-26 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='소셜 고유 ID')),
                ('provider', models.CharField(blank=True, choices=[('github', 'GitHub'), ('google', 'Google'), ('kakao', 'Kakao'), ('naver', 'Naver')], max_length=50, null=True, verbose_name='소셜 제공처')),
                ('profile_image_url', models.URLField(blank=True, null=True, verbose_name='프로필 이미지 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자 계정')),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필 목록',
                'db_table': 'user_profiles',
            },
        ),
    ]
