# Generated by Django 5.0.6 on 2026-05-26 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('learning', '0002_alter_curriculum_options_remove_quizchoice_choice_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelectedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True, verbose_name='선택 일시')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.job', verbose_name='선택한 직무')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile', verbose_name='사용자 프로필')),
            ],
            options={
                'verbose_name': '사용자 관심 직무',
                'verbose_name_plural': '사용자 관심 직무 목록',
                'db_table': 'user_selected_job',
                'unique_together': {('user_profile', 'job')},
            },
        ),
    ]
