# Generated by Django 5.0.6 on 2026-05-26 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum_step', models.CharField(max_length=30, verbose_name='단계 식별자')),
                ('topic', models.TextField(verbose_name='주제')),
                ('objectives', models.TextField(verbose_name='학습 목표')),
                ('key_contents', models.TextField(verbose_name='학습 내용')),
            ],
            options={
                'verbose_name': '커리큘럼 단계',
                'verbose_name_plural': '커리큘럼 단계 목록',
                'db_table': 'curriculum',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=30, verbose_name='직무명')),
                ('job_desc', models.TextField(verbose_name='직무 설명')),
            ],
            options={
                'verbose_name': '직무',
                'verbose_name_plural': '직무 목록',
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=30, verbose_name='기술명')),
                ('skill_desc', models.TextField(verbose_name='기술 설명')),
                ('skill_level', models.CharField(max_length=10, verbose_name='기술 레벨')),
            ],
            options={
                'verbose_name': '기술',
                'verbose_name_plural': '기술 목록',
                'db_table': 'skill',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(max_length=10, verbose_name='난이도')),
                ('question', models.TextField(verbose_name='문제 내용')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='learning.curriculum', verbose_name='대상 커리큘럼')),
            ],
            options={
                'verbose_name': '퀴즈 문제',
                'verbose_name_plural': '퀴즈 문제 목록',
                'db_table': 'quizquestion',
            },
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_no', models.SmallIntegerField(verbose_name='보기 번호')),
                ('choice_text', models.TextField(verbose_name='보기 내용')),
                ('is_correct', models.BooleanField(verbose_name='정답 여부')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='해설')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='learning.quizquestion', verbose_name='대상 문제')),
            ],
            options={
                'verbose_name': '퀴즈 보기',
                'verbose_name_plural': '퀴즈 보기 목록',
                'db_table': 'quizchoice',
            },
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_nodes', to='learning.job', verbose_name='대상 직무')),
                ('parent_roadmap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_roadmaps', to='learning.roadmap', verbose_name='선행 로드맵 노드')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_as_skill', to='learning.skill', verbose_name='대상 기술')),
            ],
            options={
                'verbose_name': '로드맵 의존성',
                'verbose_name_plural': '로드맵 의존성 목록',
                'db_table': 'roadmap',
            },
        ),
        migrations.AddField(
            model_name='curriculum',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='learning.skill', verbose_name='대상 기술'),
        ),
    ]
