# Generated by Django 5.0.6 on 2026-05-26 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculum',
            options={'ordering': ['skill', 'curriculum_step'], 'verbose_name': '커리큘럼 단계', 'verbose_name_plural': '커리큘럼 단계 목록'},
        ),
        migrations.RemoveField(
            model_name='quizchoice',
            name='choice_no',
        ),
        migrations.AlterUniqueTogether(
            name='roadmap',
            unique_together={('job', 'skill', 'parent_roadmap_id')},
        ),
        migrations.AddField(
            model_name='job',
            name='job_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='AI 일러스트 이미지 URL'),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='parent_roadmap_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_as_parent_roadmap_id', to='learning.skill', verbose_name='선행 기술'),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_icon_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Devicon/Lucide 아이콘 코드'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_desc',
            field=models.TextField(blank=True, null=True, verbose_name='직무 설명'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='직무명'),
        ),
        migrations.AlterField(
            model_name='quizchoice',
            name='choice_text',
            field=models.CharField(max_length=255, verbose_name='선택지 내용'),
        ),
        migrations.AlterField(
            model_name='quizchoice',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='정답 해설'),
        ),
        migrations.AlterField(
            model_name='quizchoice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='정답 여부'),
        ),
        migrations.AlterField(
            model_name='quizchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='learning.quizquestion', verbose_name='소속 문제'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='difficulty',
            field=models.CharField(choices=[('easy', '쉬움 (15점)'), ('medium', '중간 (20점)'), ('hard', '어려움 (30점)')], default='medium', max_length=10, verbose_name='난이도'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question',
            field=models.TextField(verbose_name='퀴즈 지문'),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_as_skill', to='learning.skill', verbose_name='대상 기술'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_desc',
            field=models.TextField(blank=True, null=True, verbose_name='기술 설명'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_level',
            field=models.CharField(max_length=20, verbose_name='기술 난이도'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='기술명'),
        ),
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together={('skill', 'curriculum_step')},
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='취득 점수 (최대 100점)')),
                ('is_passed', models.BooleanField(default=False, verbose_name='통과 여부 (70점 기준)')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, verbose_name='제출 시간')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.skill', verbose_name='대상 기술')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '퀴즈 시도 이력',
                'verbose_name_plural': '퀴즈 시도 이력 목록',
                'db_table': 'quiz_attempts',
            },
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(verbose_name='정답 일치 여부')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='learning.quizattempt', verbose_name='퀴즈 세션 시도')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.quizquestion', verbose_name='푼 문제')),
                ('selected_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.quizchoice', verbose_name='선택한 보기')),
            ],
            options={
                'verbose_name': '사용자 문항 답안',
                'verbose_name_plural': '사용자 문항 답안 목록',
                'db_table': 'user_responses',
            },
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='parent_roadmap',
        ),
        migrations.CreateModel(
            name='UserBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='북마크 시간')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='learning.curriculum', verbose_name='북마크 커리큘럼')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 북마크',
                'verbose_name_plural': '사용자 북마크 목록',
                'db_table': 'user_bookmarks',
                'unique_together': {('user', 'curriculum')},
            },
        ),
        migrations.CreateModel(
            name='UserCurriculumProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 일시')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='learning.curriculum', verbose_name='커리큘럼 단계')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_progresses', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 진도 상태',
                'verbose_name_plural': '사용자 진도 상태 목록',
                'db_table': 'user_curriculum_progresses',
                'unique_together': {('user', 'curriculum')},
            },
        ),
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='메모 본문')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 수정일')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='learning.curriculum', verbose_name='메모 대상 커리큘럼')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 메모',
                'verbose_name_plural': '사용자 메모 목록',
                'db_table': 'user_notes',
                'unique_together': {('user', 'curriculum')},
            },
        ),
    ]
